-- Prerequisites: enable pgvector in target DB first
-- Supabase SQL Editor: Extensions → search "vector" → enable

-- ============================================================
-- Tables
-- ============================================================
CREATE TABLE public.documents (
  id bigserial NOT NULL,
  content text NULL,
  metadata jsonb NULL,
  -- 1536 dims = OpenAI text-embedding-3-small; HNSW requires a typed dimension
  embedding public.vector(1536) NULL,
  fts tsvector GENERATED ALWAYS AS (
    to_tsvector('english'::regconfig, COALESCE(content, ''::text))
  ) STORED NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.record_manager (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  doc_id text NOT NULL,
  hash text NOT NULL,
  CONSTRAINT record_manager_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE public.chat_logs (
  id bigserial NOT NULL,
  session_id text NOT NULL,
  chat_input text NOT NULL,
  answer text NULL,
  source_metadata jsonb NULL,
  needs_human boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chat_logs_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS documents_fts_idx
  ON public.documents USING gin (fts) TABLESPACE pg_default;

-- vector_cosine_ops matches the <=> operator used in hybrid_search_with_details;
-- an inner-product (vector_ip_ops) index would never be used by cosine queries
CREATE INDEX IF NOT EXISTS documents_embedding_idx
  ON public.documents USING hnsw (embedding vector_cosine_ops) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_chat_logs_session
  ON public.chat_logs USING btree (session_id, created_at) TABLESPACE pg_default;